# Download most recent production database dump and restore it.

- hosts: all
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  become: yes
  become_method: sudo
  tasks:
    - name: ensure aws configuration directory is present
      file:
        dest: /root/.aws
        state: directory
      when: "{{env == 'development'}}"

    - name: ensure aws creds are on machine so database dumps can be downloaded
      template:
        src: credentials.j2
        dest: /root/.aws/credentials
      when: "{{env == 'development'}}"

    - name: download latest database dump
      command: aws s3 cp s3://{{backup_bucket}}/current /tmp
      args:
        creates: /tmp/current

    - name: restore database dump
      become: yes
      become_user: postgres
      shell: |
        dropdb {{env_vars[env].PGNAME}}
        createdb {{env_vars[env].PGNAME}} -O {{env_vars[env].PGUSER}}
        pg_restore -d {{env_vars[env].PGNAME}} current
      args:
        chdir: /tmp
