- hosts: all
  vars_files:
    - vars/main.yml
    - vars/{{env}}.yml
  become: yes
  become_method: sudo
  tasks:
    - name: download latest database dump
      command: aws s3 cp s3://{{backup_bucket}}/current /tmp
      args:
        creates: /tmp/current

    - name: restore database dump
      become: yes
      become_user: postgres
      shell: |
        dropdb {{env_vars.PGNAME}}
        createdb {{env_vars.PGNAME}} -O {{env_vars.PGUSER}}
        pg_restore -d {{env_vars.PGNAME}} current
      args:
        chdir: /tmp
