- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  vars_files:
    - vars/main.yml
  handlers:
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded
    - name: letsencrypt initial run
      command: "dehydrated --cron"
      register: dehydrated
      changed_when: "'Done!' in dehydrated.stdout"
      notify: reload nginx
  tasks:
    # Start managing system packages and updates.
    - name: ensure python is installed
      raw: apt-get update && apt-get install -y python

    - name: ensure apt keys have been added
      apt_key:
        url: "{{item}}"
        state: present
      with_items:
        - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        - https://www.postgresql.org/media/keys/ACCC4CF8.asc
        - https://dl.yarnpkg.com/debian/pubkey.gpg

    - name: ensure apt repositories have been added
      apt_repository:
        repo: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - ppa:git-core/ppa
        - deb https://deb.nodesource.com/node_6.x trusty main
        - deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main
        - deb https://dl.yarnpkg.com/debian/ stable main

    - name: ensure apt packages have been installed
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      with_items:
        - build-essential # for building native deps in node
        - nginx # for serving files

    # Start managing networking.
    - name: ensure hostname is set
      hostname:
        name: "{{hostname}}"

    - name: ensure loopback references have been created in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "127.0.0.1 {{hostname}} {{fqdn}}"
    # End managing networking.

    # Start managing nginx.
    - name: ensure ssl cert paths exist
      file:
        path: "{{cert_path}}/{{item}}"
        state: directory
      with_items: "{{ [fqdn] + alias_domains }}"

    - name: create self-signed ssl certs/keys if no certs exist
      command: >
        openssl req -new -nodes -x509 -extensions v3_ca -days 3650
        -subj "/C=US/ST=Massachusetts/L=Boston/O=IT/CN={{item}}"
        -keyout {{cert_path}}/{{item}}/{{ssl_key_file}}
        -out {{cert_path}}/{{item}}/{{ssl_cert_file}}
      args:
        creates: "{{cert_path}}/{{item}}/{{ssl_cert_file}}"
      with_items: "{{ [fqdn] + alias_domains }}"
      notify: reload nginx

    - name: ensure default nginx config is absent
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: reload nginx

    - name: ensure nginx is configured
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-enabled/site.conf
      notify: reload nginx

    - name: ensure htpasswd is configured
      template:
        src: htpasswd.j2
        dest: /etc/nginx/htpasswd
      when: "{{basic_auth}}"
      notify: reload nginx

    - include: ssl.yml
      when: "{{env == 'production'}}"
    # End managing nginx.
